import { expect, it } from "vitest";
import { assertFreshParserVersionParity } from "./claude-parser-version-parity.js";

const sourceId = "h1:" + "a".repeat(32) + ":source:" + "b".repeat(64);
const capabilities = (parserVersion: number, provider = "claude") => ({ provider, parserVersion, support: "shape_verified_only", coverage: "partial" });
const processResult = (stdout: string, status = 0) => ({ status, stdout, stderr: "" });
const json = (command: string, result: unknown) => processResult(JSON.stringify({ schema: "agentprof.cli/v1", ok: true, command, result }) + "\n");
// The two versions below are authored oracles, never output generated by the parity helper.
const scan = (version: number) => json("scan", { sources: [{ provider: "claude", capabilities: capabilities(version) }], counts: { committed: 1 }, aggregationReady: false });
const summary = (version: number) => json("stats", { mode: "selected_source", summary: { schema: "agentprof.source-summary/v1", provider: "claude", capabilities: capabilities(version),
  inventory: { events: 6 }, durations: [{ n: 5, sumMs: 20 }], usage: [{ counts: { input: 100, output: 20 } }], diagnostics: [{ code: "SAFE_DIAGNOSTIC", byteOffset: 12 }],
  normalizationVersion: 1, keyVersion: 1, parserResumeReady: false, note: "literal parserVersion:1 must remain unchanged" } });
const analysis = (version: number, command: string, mode: string, schema: string) => json(command, { mode, analysis: { schema, provider: "claude", parserVersion: version,
  normalizationVersion: 1, keyVersion: 1, capabilities: capabilities(version), inventory: { events: 6 }, partitions: [{ sumMs: 20 }], limitation: "parser version 1 is historical" } });
const catalogue = json("stats", { mode: "list_sources", catalogue: { schema: "agentprof.source-catalogue/v1", items: [{ provider: "claude", revision: 1 }], parserResumeReady: false } });
const jsonCases = [
  { name: "scan", args: ["scan", "--claude-root", "/synthetic"], old: scan(1), current: scan(2) },
  { name: "summary", args: ["stats", "--source", sourceId], old: summary(1), current: summary(2) },
  { name: "insights", args: ["insights", "--source", sourceId], old: analysis(1, "insights", "selected_source", "agentprof.source-slow-tool/v1"), current: analysis(2, "insights", "selected_source", "agentprof.source-slow-tool/v1") },
  { name: "failures", args: ["stats", "--source", sourceId, "--failures"], old: analysis(1, "stats", "selected_source_failures", "agentprof.source-failures/v1"), current: analysis(2, "stats", "selected_source_failures", "agentprof.source-failures/v1") },
  { name: "read revisits", args: ["stats", "--read-revisits", "--source", sourceId], old: analysis(1, "stats", "selected_source_read_revisits", "agentprof.source-read-revisits/v1"), current: analysis(2, "stats", "selected_source_read_revisits", "agentprof.source-read-revisits/v1") },
];
const humanCases = [
  { name: "summary", args: ["stats", "--source", sourceId], old: "AgentProf stored source-prefix stats\nSupport: shape_verified_only; coverage: partial; parser version: 1\nCount: 1\n",
    current: "AgentProf stored source-prefix stats\nSupport: shape_verified_only; coverage: partial; parser version: 2\nCount: 1\n" },
  { name: "insights", args: ["insights", "--source", sourceId], old: "AgentProf stored source-prefix insights\nVersions: parser=1; normalization=1; key=1\nSupport: shape_verified_only; coverage: recognized_shapes; capability parser version=1\nCount: 1\n",
    current: "AgentProf stored source-prefix insights\nVersions: parser=2; normalization=1; key=1\nSupport: shape_verified_only; coverage: recognized_shapes; capability parser version=2\nCount: 1\n" },
  { name: "failures", args: ["stats", "--failures", "--source", sourceId], old: "AgentProf confirmed source-local failure evidence\nParser/normalization/key=1/1/1; support=shape_verified_only; no freshness or cross-source check\nCount: 1\n",
    current: "AgentProf confirmed source-local failure evidence\nParser/normalization/key=2/1/1; support=shape_verified_only; no freshness or cross-source check\nCount: 1\n" },
  { name: "read revisits", args: ["stats", "--source", sourceId, "--read-revisits"], old: "AgentProf completed source-local Read revisits\nAssessment=partial; suppression=none; parser/normalization/key=1/1/1\nCount: 1\n",
    current: "AgentProf completed source-local Read revisits\nAssessment=partial; suppression=none; parser/normalization/key=2/1/1\nCount: 1\n" },
];
it.each(jsonCases)("permits only authored fresh Claude JSON version fields: $name", c => {
  assertFreshParserVersionParity("claude", [...c.args, "--json"], c.current, c.old);
});
it.each(humanCases)("permits only authored fresh Claude human version lines: $name", c => {
  assertFreshParserVersionParity("claude", c.args, processResult(c.current), processResult(c.old));
});
it.each(["scan", "catalogue", "Codex"])("retains exact unchanged bytes for %s", name => {
  if (name === "Codex") { const output = json("scan", { capabilities: capabilities(1, "codex") }); assertFreshParserVersionParity("codex", ["scan", "--codex-root", "/synthetic", "--json"], output, output); }
  else if (name === "catalogue") assertFreshParserVersionParity("claude", ["stats", "--list-sources", "--json"], catalogue, catalogue);
  else { const output = processResult("Scan: partial\nSources: committed=1\n", 1); assertFreshParserVersionParity("claude", ["scan", "--claude-root", "/synthetic"], output, output); }
});
it("does not mutate the historical process receipt", () => {
  const old = Object.freeze(summary(1)), before = { ...old };
  assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], summary(2), old);
  expect(old).toEqual(before);
});

function changed(output: ReturnType<typeof processResult>, mutate: (payload: any) => void) {
  const payload = JSON.parse(output.stdout); mutate(payload);
  return { ...output, stdout: JSON.stringify(payload) + "\n" };
}
const payloadChanges = [
  ["event count", (p: any) => { p.result.summary.inventory.events++; }],
  ["duration", (p: any) => { p.result.summary.durations[0].sumMs++; }],
  ["usage", (p: any) => { p.result.summary.usage[0].counts.input++; }],
  ["diagnostic", (p: any) => { p.result.summary.diagnostics[0].byteOffset++; }],
  ["normalization version", (p: any) => { p.result.summary.normalizationVersion = 2; }],
  ["key version", (p: any) => { p.result.summary.keyVersion = 2; }],
  ["readiness", (p: any) => { p.result.summary.parserResumeReady = true; }],
  ["unrelated literal", (p: any) => { p.result.summary.note = "literal parserVersion:2 must remain unchanged"; }],
  ["extra version field", (p: any) => { p.result.summary.inventory.parserVersion = 2; }],
  ["wrong provider", (p: any) => { p.result.summary.provider = "codex"; }],
  ["wrong mode", (p: any) => { p.result.mode = "other"; }],
  ["wrong schema", (p: any) => { p.schema = "agentprof.cli/v2"; }],
  ["wrong command", (p: any) => { p.command = "insights"; }],
  ["unknown current version", (p: any) => { p.result.summary.capabilities.parserVersion = 3; }],
  ["unchanged current version", (p: any) => { p.result.summary.capabilities.parserVersion = 1; }],
  ["missing version", (p: any) => { delete p.result.summary.capabilities.parserVersion; }],
] as const;
it.each(payloadChanges)("rejects current JSON change outside the exception: %s", (_name, mutate) => {
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], changed(summary(2), mutate), summary(1))).toThrow();
});
it.each([null, 2, 130])("rejects changed process exit status: %s", status => {
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], { ...summary(2), status }, summary(1))).toThrow();
});
it("rejects changed stderr", () => {
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], { ...summary(2), stderr: "warning\n" }, summary(1))).toThrow();
});
it.each([0, 2, 3, "1", null])("rejects historical capability version %s", version => {
  const old = changed(summary(1), p => { p.result.summary.capabilities.parserVersion = version; });
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], summary(2), old)).toThrow();
});
it.each(["analysis", "capability"])("requires each analysis version to be exactly historical 1: %s", where => {
  const c = jsonCases[2]!, old = changed(c.old, p => { if (where === "analysis") p.result.analysis.parserVersion = 3; else p.result.analysis.capabilities.parserVersion = 3; });
  expect(() => assertFreshParserVersionParity("claude", [...c.args, "--json"], c.current, old)).toThrow();
});
it.each(["summary", "catalogue"])("rejects extra historical parser-version locations even when both outputs agree there: %s", where => {
  if (where === "summary") {
    const add = (p: any) => { p.result.summary.inventory.parserVersion = 1; };
    expect(() => assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], changed(summary(2), add), changed(summary(1), add))).toThrow();
  } else {
    const output = changed(catalogue, p => { p.result.catalogue.items[0].parserVersion = 1; });
    expect(() => assertFreshParserVersionParity("claude", ["stats", "--list-sources", "--json"], output, output)).toThrow();
  }
});
it.each(["counts", "parserVersion"])("preserves unchanged-version catalogue fields exactly: %s", field => {
  const current = changed(catalogue, p => { p.result.catalogue.items[0][field] = 2; });
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--list-sources", "--json"], current, catalogue)).toThrow();
});
it.each(["version", "status", "stderr"])("never normalizes a Codex change: %s", field => {
  const old = json("scan", { capabilities: capabilities(1, "codex") });
  const current = field === "version" ? json("scan", { capabilities: capabilities(2, "codex") }) : field === "status" ? { ...old, status: 1 } : { ...old, stderr: "warning\n" };
  expect(() => assertFreshParserVersionParity("codex", ["scan", "--codex-root", "/synthetic", "--json"], current, old)).toThrow();
});
it.each(["space", "duplicate key", "escaped key", "CRLF"])("rejects noncanonical historical JSON: %s", form => {
  const old = summary(1), stdout = form === "space" ? " " + old.stdout : form === "duplicate key" ? old.stdout.replace('"command":"stats"', '"command":"stats","command":"stats"')
    : form === "escaped key" ? old.stdout.replace('"schema"', '"\\u0073chema"') : old.stdout.replace(/\n$/, "\r\n");
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], summary(2), { ...old, stdout })).toThrow();
});
it.each(["space", "key order", "extra newline"])("rejects current JSON formatting change: %s", form => {
  const current = summary(2), stdout = form === "space" ? " " + current.stdout : form === "extra newline" ? current.stdout + "\n"
    : current.stdout.replace('"schema":"agentprof.cli/v1","ok":true', '"ok":true,"schema":"agentprof.cli/v1"');
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--source", sourceId, "--json"], { ...current, stdout }, summary(1))).toThrow();
});
it.each(humanCases)("rejects any extra human text or numeric change: $name", c => {
  expect(() => assertFreshParserVersionParity("claude", c.args, processResult(c.current.replace("Count: 1", "Count: 2")), processResult(c.old))).toThrow();
});
it.each(humanCases)("rejects missing, duplicated and future human version lines: $name", c => {
  const versionLine = c.old.split("\n").find(line => /parser(?: version|=|\/normalization)/i.test(line))!;
  for (const old of [c.old.replace(versionLine + "\n", ""), c.old + versionLine + "\n", c.old.replace(versionLine, versionLine.replace(/(?:=|: )1/, text => text.replace("1", "3")))]) {
    expect(() => assertFreshParserVersionParity("claude", c.args, processResult(c.current), processResult(old))).toThrow();
  }
});
it.each(["normalization", "key"])("does not promote the human %s version", field => {
  const c = humanCases[1]!, current = c.current.replace(`${field}=1`, `${field}=2`);
  expect(() => assertFreshParserVersionParity("claude", c.args, processResult(current), processResult(c.old))).toThrow();
});
it("retains exact human scan output", () => {
  expect(() => assertFreshParserVersionParity("claude", ["scan", "--claude-root", "/synthetic"], processResult("Scan: partial\ncommitted=2\n"), processResult("Scan: partial\ncommitted=1\n"))).toThrow();
});
it("rejects an unreviewed command selection", () => {
  expect(() => assertFreshParserVersionParity("claude", ["stats", "--invocation-overlap", "--source", sourceId, "--json"], summary(2), summary(1))).toThrow();
});
