import { appendFile,writeFile } from "node:fs/promises";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { afterEach,expect,it,vi } from "vitest";
import { openDatabase } from "../src/db/database.js";
import { createSourceStore } from "../src/db/source-store.js";
import { CodexAdapter,createCodexAdapter,DEFAULT_CODEX_LIMITS } from "../src/parsers/codex/index.js";
import * as codexCodec from "../src/parsers/codex/checkpoint.js";
import { DEFAULT_CLAUDE_LIMITS } from "../src/parsers/claude/index.js";
import * as ingestion from "../src/scanner/source-ingest.js";
import { temporaryDirectory } from "./helpers.js";
import { context,keyId,ordinary,wrappers,meta,call,cold,encode,allRows,projection,seal,resign,sha,hmac } from "./codex-resume-fixture.js";
const databases=new Set<DatabaseSync>();
afterEach(()=>{vi.restoreAllMocks();for(const db of databases){try{db.close();}catch{}}databases.clear();});
async function fixture(records:readonly unknown[]=ordinary.slice(0,2),maxFileBytes=64*1024*1024){const root=temporaryDirectory(),path=join(root,"source.jsonl"),data=join(root,"data");await writeFile(path,encode(records));const db=await openDatabase(data);databases.add(db);const store=createSourceStore(db,keyId),first=await ingestion.ingestSourceFile(store,context,{path,provider:"codex",expectedRevision:null,maxFileBytes});expect(first.status).toBe("committed");const candidate=store.readSourceForIngestion(first.sourceId,context);expect(candidate.checkpoint,"MISSING_CODEX_DURABLE_CAPTURE").not.toBeNull();return{root,path,data,db,store,id:first.sourceId,candidate};}
function input(source:any){const{revision,availability,persistedScope,aggregationReady,parserResumeReady,...value}=source;return value;}
function capture(db:DatabaseSync,id:string){const r:any=db.prepare("SELECT * FROM source_parser_checkpoints WHERE source_id=?").get(id);return{checkpoint:r.checkpoint_json,nextOrdinal:r.next_ordinal,maxFileBytes:r.max_file_bytes,maxRecords:r.max_records,maxLineBytes:r.max_line_bytes};}
function intercept(db:DatabaseSync,table:string,action:()=>void){const prepare=db.prepare.bind(db);db.prepare=((sql:string)=>{const statement=prepare(sql);if(!new RegExp(`INSERT(?: OR [A-Z]+)? INTO ${table}\\b`,"i").test(sql))return statement;return new Proxy(statement,{get(target,p){if(p==="run")return(...args:any[])=>{const value=(target.run as any)(...args);action();return value;};const value=Reflect.get(target,p);return typeof value==="function"?value.bind(target):value;}});})as typeof db.prepare;return()=>{db.prepare=prepare;};}
it("schema6 reuse, independent Codex domains and exact existing Claude seal",async()=>{
 const f=await fixture();expect(f.db.prepare("PRAGMA user_version").get()?.user_version).toBe(8);const row:any=f.db.prepare("SELECT * FROM source_parser_checkpoints WHERE source_id=?").get(f.id);expect(row.generation_seal).toBe(seal(f.db,f.id));expect(row.adapter_limits_fingerprint).toBe(sha(JSON.stringify(["agentprof.codex-limits/v1",Object.entries(DEFAULT_CODEX_LIMITS)])));expect(row.checkpoint_bytes).toBe(Buffer.byteLength(row.checkpoint_json));expect(row.next_ordinal).toBe(2);
 const path=join(f.root,"claude.jsonl"),record={type:"assistant",uuid:"u",sessionId:"FICTITIOUS_CLAUDE",timestamp:"2026-09-01T00:00:00.000Z",message:{id:"r",role:"assistant",content:[{type:"tool_use",id:"c",name:"Bash",input:{command:"npm test"}}]}};await writeFile(path,encode([record]));const first=await ingestion.ingestSourceFile(f.store,context,{path,provider:"claude",expectedRevision:null});expect(first.status).toBe("committed");const c:any=f.db.prepare("SELECT * FROM source_parser_checkpoints WHERE source_id=?").get(first.sourceId);expect(c.generation_seal).toBe(seal(f.db,first.sourceId,"claude"));expect(c.adapter_limits_fingerprint).toBe(sha(JSON.stringify(["agentprof.claude-limits/v1",Object.entries(DEFAULT_CLAUDE_LIMITS)])));
 expect(f.store.readSourceForIngestion(f.id,context).checkpoint!.generationSeal).toBe(row.generation_seal);expect(f.store.readSourceForIngestion(first.sourceId,context).checkpoint!.generationSeal).toBe(c.generation_seal);
 f.db.prepare("UPDATE source_parser_checkpoints SET checkpoint_json=?,checkpoint_bytes=? WHERE source_id=?").run(c.checkpoint_json,c.checkpoint_bytes,f.id);resign(f.db,f.id);const before=allRows(f.db);expect(()=>f.store.readSourceForIngestion(f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(allRows(f.db)).toEqual(before);expect(f.store.readSourceForIngestion(first.sourceId,context).checkpoint!.generationSeal).toBe(c.generation_seal);
 f.db.prepare("UPDATE source_parser_checkpoints SET checkpoint_json=?,checkpoint_bytes=? WHERE source_id=?").run(row.checkpoint_json,row.checkpoint_bytes,first.sourceId);f.db.prepare("UPDATE source_parser_checkpoints SET generation_seal=? WHERE source_id=?").run(seal(f.db,first.sourceId,"claude"),first.sourceId);const inverse=allRows(f.db);expect(()=>f.store.readSourceForIngestion(first.sourceId,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(allRows(f.db)).toEqual(inverse);
});
it.each(["source_event_headers","source_event_contributions","source_metric_headers","source_metric_contributions","source_relationship_headers","source_relationship_contributions","source_cache_evidence","source_parser_checkpoints"])("SQL exception after %s insert rolls back entire Codex generation",async table=>{
 const f=await fixture(),before=allRows(f.db),source=input(f.candidate.source),checkpoint=capture(f.db,f.id);let hits=0;
 const undo=intercept(f.db,table,()=>{hits++;throw Error("FICTITIOUS_INSERT_FAILURE");});try{expect(()=>f.store.replaceSourceSnapshotWithCheckpoint(source,checkpoint,context,1,f.candidate.predecessor)).toThrow();}finally{undo();}
 expect(hits,"actual target INSERT must execute before injected failure").toBe(1);expect(allRows(f.db)).toEqual(before);expect(f.db.isTransaction).toBe(false);
 expect(f.store.replaceSourceSnapshotWithCheckpoint(source,checkpoint,context,1,f.candidate.predecessor)).toMatchObject({status:"committed",revision:2});expect(f.store.readSourceForIngestion(f.id,context).checkpoint).not.toBeNull();
});
it("abort after actual checkpoint insertion rolls back",async()=>{const f=await fixture(),before=allRows(f.db),source=input(f.candidate.source),checkpoint=capture(f.db,f.id),controller=new AbortController();let hits=0;const undo=intercept(f.db,"source_parser_checkpoints",()=>{hits++;controller.abort();});try{expect(f.store.replaceSourceSnapshotWithCheckpoint(source,checkpoint,context,1,f.candidate.predecessor,controller.signal)).toEqual({status:"aborted"});}finally{undo();}expect(hits).toBe(1);expect(allRows(f.db)).toEqual(before);expect(f.store.replaceSourceSnapshotWithCheckpoint(source,checkpoint,context,1,f.candidate.predecessor)).toMatchObject({status:"committed",revision:2});});
it.each(["bytes","blob","oversize","negative","duplicate","orphan","seal","token"])("bounded corrupt %s row is hard failure without repair",async kind=>{
 const f=await fixture();f.db.exec("ALTER TABLE source_parser_checkpoints RENAME TO constrained_checkpoint; CREATE TABLE source_parser_checkpoints AS SELECT * FROM constrained_checkpoint; DROP TABLE constrained_checkpoint");
 if(kind==="bytes")f.db.exec("UPDATE source_parser_checkpoints SET checkpoint_bytes=checkpoint_bytes+1");if(kind==="blob")f.db.exec("UPDATE source_parser_checkpoints SET checkpoint_json=CAST(checkpoint_json AS BLOB)");if(kind==="oversize")f.db.exec("UPDATE source_parser_checkpoints SET checkpoint_json=CAST(zeroblob(4194305) AS TEXT),checkpoint_bytes=4194305");if(kind==="negative")f.db.exec("UPDATE source_parser_checkpoints SET next_ordinal=-1");if(kind==="duplicate")f.db.exec("INSERT INTO source_parser_checkpoints SELECT * FROM source_parser_checkpoints");if(kind==="orphan")f.db.prepare("UPDATE source_parser_checkpoints SET source_id=?").run(hmac("source","absent"));if(kind==="seal")f.db.prepare("UPDATE source_parser_checkpoints SET generation_seal=?").run(hmac("source","wrong"));if(kind==="token")f.db.exec("UPDATE source_parser_checkpoints SET checkpoint_json='FICTITIOUS_CORRUPTION',checkpoint_bytes=21");const before=allRows(f.db);expect(()=>f.store.readSourceForIngestion(kind==="orphan"?hmac("source","absent"):f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(allRows(f.db)).toEqual(before);
});
it.each(["resume","limits","mismatch","export_unavailable"])("same-revision checkpoint deletion on %s cannot overwrite predecessor",async route=>{
 const f=await fixture();await appendFile(f.path,encode(ordinary.slice(2)));if(route==="mismatch")await writeFile(f.path,encode(ordinary.slice(0,1)));if(route==="export_unavailable")vi.spyOn(CodexAdapter.prototype,"exportCheckpoint").mockReturnValue({status:"unavailable",reason:"checkpoint_budget"});
 const peer=new DatabaseSync(join(f.data,"agentprof.sqlite"));databases.add(peer);peer.exec("DELETE FROM source_parser_checkpoints");const before=allRows(peer);await expect(ingestion.ingestSourceFileFromCheckpoint(f.store,context,{path:f.path,provider:"codex",expectedRevision:1,...(route==="limits"?{maxRecords:99}:{})},f.candidate)).rejects.toMatchObject({code:"DATABASE_ACCESS_FAILED"});expect(allRows(peer)).toEqual(before);
});
it("same-revision absent-to-present insertion retains original absence CAS",async()=>{const f=await fixture(),row:any=f.db.prepare("SELECT * FROM source_parser_checkpoints").get();f.db.exec("DELETE FROM source_parser_checkpoints");const absent=f.store.readSourceForIngestion(f.id,context);expect(absent.checkpoint).toBeNull();const names=Object.keys(row);f.db.prepare(`INSERT INTO source_parser_checkpoints(${names.join(",")}) VALUES(${names.map(()=>"?").join(",")})`).run(...Object.values(row)as any[]);const before=allRows(f.db);await expect(ingestion.ingestSourceFileFromCheckpoint(f.store,context,{path:f.path,provider:"codex",expectedRevision:1},absent)).rejects.toMatchObject({code:"DATABASE_ACCESS_FAILED"});expect(allRows(f.db)).toEqual(before);});
it("peer revision advance is stale, with no candidate refresh",async()=>{const f=await fixture(),peer=new DatabaseSync(join(f.data,"agentprof.sqlite"));databases.add(peer);createSourceStore(peer,keyId).markUnavailable(f.id,1);const before=allRows(peer),read=vi.fn(f.store.readSourceForIngestion);expect(await ingestion.ingestSourceFileFromCheckpoint({...f.store,readSourceForIngestion:read},context,{path:f.path,provider:"codex",expectedRevision:1},f.candidate)).toMatchObject({status:"stale",actualRevision:2});expect(read).not.toHaveBeenCalled();expect(allRows(peer)).toEqual(before);});
it("valid historical adapter limits replay; corrupt seal overrides incompatibility",async()=>{const f=await fixture();f.db.prepare("UPDATE source_parser_checkpoints SET adapter_limits_fingerprint=?").run("a".repeat(64));resign(f.db,f.id);const old=f.store.readSourceForIngestion(f.id,context),spy=vi.spyOn(CodexAdapter.prototype,"ingest");expect((await ingestion.ingestSourceFileFromCheckpoint(f.store,context,{path:f.path,provider:"codex",expectedRevision:1},old)).status).toBe("committed");expect(spy).toHaveBeenCalledTimes(2);f.db.prepare("UPDATE source_parser_checkpoints SET adapter_limits_fingerprint=?,generation_seal=?").run("a".repeat(64),hmac("source","invalid"));const before=allRows(f.db);expect(()=>f.store.readSourceForIngestion(f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(allRows(f.db)).toEqual(before);});
it("optional checkpoint absence uses full replay and captures on changed source",async()=>{const f=await fixture();f.db.exec("DELETE FROM source_parser_checkpoints");const absent=f.store.readSourceForIngestion(f.id,context);await appendFile(f.path,encode(ordinary.slice(2)));const spy=vi.spyOn(CodexAdapter.prototype,"ingest");expect((await ingestion.ingestSourceFileFromCheckpoint(f.store,context,{path:f.path,provider:"codex",expectedRevision:1},absent)).status).toBe("committed");expect(spy).toHaveBeenCalledTimes(4);expect(f.store.readSourceForIngestion(f.id,context).checkpoint!.nextOrdinal).toBe(4);});
it("export unavailable commits evidence while atomically clearing optional state",async()=>{const f=await fixture();await appendFile(f.path,encode(ordinary.slice(2)));vi.spyOn(CodexAdapter.prototype,"exportCheckpoint").mockReturnValue({status:"unavailable",reason:"checkpoint_budget"});expect(await ingestion.ingestSourceFileFromCheckpoint(f.store,context,{path:f.path,provider:"codex",expectedRevision:1},f.candidate)).toMatchObject({status:"committed",revision:2});const next=f.store.readSourceForIngestion(f.id,context);expect(next.checkpoint).toBeNull();expect(next.source!.events[0]).toMatchObject({status:"completed",durationMs:4000});});
it("unchanged scan confirms original optional checkpoint presence",async()=>{
 const f=await fixture(undefined,16*1024*1024);let mutations=0,before:any;const facade={...f.store,confirmUnchangedSourceWithCheckpoint(token:any,predecessor:any,c:any,signal?:AbortSignal){expect(predecessor.checkpointSeal).toBe(f.candidate.predecessor.checkpointSeal);f.db.exec("DELETE FROM source_parser_checkpoints");mutations++;before=allRows(f.db);return f.store.confirmUnchangedSourceWithCheckpoint(token,predecessor,c,signal);}};
 const {scanSources}=await import("../src/scanner/scan-run.js");const outcome=await scanSources(facade,context,[{provider:"codex",path:f.path}]);expect(mutations).toBe(1);expect(outcome).toMatchObject({stopReason:"storage_failure",counts:{failed:1,unchanged:0,committed:0}});expect(allRows(f.db)).toEqual(before);
});
it("valid public-row substitution with resigned outer seal fails restored projection",async()=>{
 const f=await fixture(),r:any=f.db.prepare("SELECT * FROM source_event_contributions WHERE source_id=? LIMIT 1").get(f.id),event=JSON.parse(r.event_json);event.commandPattern="rg --hidden <args>";const next=JSON.stringify(event);f.db.prepare("UPDATE source_event_contributions SET event_json=? WHERE source_id=? AND event_id=?").run(next,f.id,r.event_id);f.db.prepare("UPDATE source_event_headers SET event_bytes=event_bytes+? WHERE source_id=?").run(Buffer.byteLength(next)-Buffer.byteLength(r.event_json),f.id);resign(f.db,f.id);expect(f.store.readSource(f.id)!.events[0]!.commandPattern).toBe("rg --hidden <args>");const before=allRows(f.db);expect(()=>f.store.readSourceForIngestion(f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(allRows(f.db)).toEqual(before);
});

it("correct-size independently resealed malformed token reaches Codex decoder and fails",async()=>{
 const f=await fixture(),token="FICTITIOUS_CORRUPTION";expect(Buffer.byteLength(token)).toBe(21);f.db.prepare("UPDATE source_parser_checkpoints SET checkpoint_json=?,checkpoint_bytes=? WHERE source_id=?").run(token,Buffer.byteLength(token),f.id);resign(f.db,f.id);const row:any=f.db.prepare("SELECT * FROM source_parser_checkpoints WHERE source_id=?").get(f.id);expect(row.generation_seal).toBe(seal(f.db,f.id));expect(row.checkpoint_bytes).toBe(Buffer.byteLength(row.checkpoint_json));const before=allRows(f.db),decode=vi.spyOn(codexCodec,"decodeCodexCheckpoint");expect(()=>f.store.readSourceForIngestion(f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(decode).toHaveBeenCalledTimes(1);expect(allRows(f.db)).toEqual(before);
});
it("valid nonempty wrapper-row substitution cannot match restored public projection",async()=>{
 const f=await fixture(wrappers),beforeSource=f.store.readSource(f.id)!;expect(beforeSource.relationshipEvidence).toMatchObject({provider:"codex",status:"captured",wrappers:[{callSeen:true,resultSeen:true}]});
 const row:any=f.db.prepare("SELECT * FROM source_relationship_contributions WHERE source_id=? AND kind='wrapper'").get(f.id),wrapper=JSON.parse(row.row_json);expect(wrapper.resultSeen).toBe(true);wrapper.resultSeen=false;const next=JSON.stringify(wrapper);f.db.prepare("UPDATE source_relationship_contributions SET row_json=? WHERE source_id=? AND kind='wrapper' AND ordinal=?").run(next,f.id,row.ordinal);f.db.prepare("UPDATE source_relationship_headers SET relationship_bytes=relationship_bytes+? WHERE source_id=?").run(Buffer.byteLength(next)-Buffer.byteLength(row.row_json),f.id);resign(f.db,f.id);expect(f.store.readSource(f.id)!.relationshipEvidence).toMatchObject({provider:"codex",wrappers:[{resultSeen:false}]});const before=allRows(f.db);expect(()=>f.store.readSourceForIngestion(f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(allRows(f.db)).toEqual(before);
});

it("real aggregate checkpoint budget refusal commits public evidence under original CAS",async()=>{
 const root=temporaryDirectory(),path=join(root,"budget.jsonl"),data=join(root,"data"),records:unknown[]=[meta],adapter=createCodexAdapter(context),sourceId=hmac("source","codex",path);let offset=0;
 const feed=(record:unknown)=>{adapter.ingest(record,{fileIdentity:path,sourceAlias:"source-1",byteOffset:offset,ordinal:records.length-1});offset+=encode([record]).length;};feed(meta);
 let lastCapturedBytes=0,lastCapturedCount=0,crossed=false;
 for(let i=0;i<90;i++){
  const record=call("exec_command",`budget-${i}`,{cmd:"rg "+"-n ".repeat(18000)});records.push(record);feed(record);
  if(i<64)continue;
  const exported=adapter.exportCheckpoint({sourceId,completedOffset:offset,nextOrdinal:records.length});
  if(exported.status==="captured"){lastCapturedBytes=Buffer.byteLength(exported.checkpoint);lastCapturedCount=records.length;continue;}
  expect(exported).toEqual({status:"unavailable",reason:"checkpoint_budget"});expect(lastCapturedCount).toBe(records.length-1);crossed=true;break;
 }
 expect(crossed).toBe(true);expect(lastCapturedBytes).toBeGreaterThan(4*1024*1024-65536);expect(lastCapturedBytes).toBeLessThanOrEqual(4*1024*1024);expect(adapter.snapshot().capabilities.stateLimited).toBe(false);expect(adapter.snapshot().capabilities.diagnosticsDropped).toBe(0);
 const prefix=encode(records.slice(0,lastCapturedCount)),all=encode(records),expected=cold(all,path).snapshot;expect(all.length).toBeLessThan(16*1024*1024);await writeFile(path,prefix);const db=await openDatabase(data);databases.add(db);const store=createSourceStore(db,keyId),exportSpy=vi.spyOn(CodexAdapter.prototype,"exportCheckpoint");
 // Pass-through spy: no mockReturnValue, real first capture and real refusal.
 const first=await ingestion.ingestSourceFile(store,context,{path,provider:"codex",expectedRevision:null,maxFileBytes:16*1024*1024});expect(first).toMatchObject({status:"committed",revision:1});expect(exportSpy).toHaveBeenCalledTimes(1);expect(exportSpy.mock.results[0]!.value.status).toBe("captured");const candidate=store.readSourceForIngestion(sourceId,context);expect(candidate.checkpoint).not.toBeNull();expect(candidate.checkpoint!.checkpointBytes).toBe(lastCapturedBytes);exportSpy.mockClear();
 await appendFile(path,all.subarray(prefix.length));const outcome=await ingestion.ingestSourceFileFromCheckpoint(store,context,{path,provider:"codex",expectedRevision:1,maxFileBytes:16*1024*1024},candidate);expect(outcome).toMatchObject({status:"committed",revision:2,capabilities:{stateLimited:false,diagnosticsDropped:0}});expect(exportSpy).toHaveBeenCalledTimes(1);expect(exportSpy.mock.results[0]!.value).toEqual({status:"unavailable",reason:"checkpoint_budget"});exportSpy.mockRestore();
 const saved=store.readSourceForIngestion(sourceId,context);expect(saved.checkpoint).toBeNull();expect(saved.source!.events).toEqual([...expected.events].sort((a,b)=>a.id.localeCompare(b.id)));expect(saved.source!.evidence).toEqual({turns:expected.turns,usage:expected.usage,observations:expected.observations,diagnostics:expected.diagnostics,capabilities:expected.capabilities});expect(saved.source!.relationshipEvidence).toEqual({contractVersion:1,capturePolicyVersion:1,status:"captured",provider:"codex",metadata:expected.metadata,wrappers:expected.wrappers});
 let total=0;for(const [table,column]of [["source_event_contributions","event_json"],["source_metric_contributions","row_json"],["source_relationship_contributions","row_json"]]){const sizes=db.prepare(`SELECT length(CAST(${column} AS BLOB)) AS bytes FROM ${table} WHERE source_id=?`).all(sourceId);for(const row of sizes){expect(Number(row.bytes)).toBeLessThan(65536);total+=Number(row.bytes);}}expect(total).toBeLessThan(16*1024*1024);
},120000);

function countRawPayloadReads(db:DatabaseSync){const prepare=db.prepare.bind(db);let reads=0;db.prepare=((sql:string)=>{const statement=prepare(sql);if(!/^\s*SELECT\s+checkpoint_json\s+FROM\s+source_parser_checkpoints\b/i.test(sql))return statement;return new Proxy(statement,{get(target,p){if(p==="get")return(...args:any[])=>{reads++;return(target.get as any)(...args);};const value=Reflect.get(target,p);return typeof value==="function"?value.bind(target):value;}});})as typeof db.prepare;return{reads:()=>reads,restore:()=>{db.prepare=prepare;}};}
it("valid checkpoint positive control selects raw payload once",async()=>{
 const f=await fixture(),before=allRows(f.db),payload=countRawPayloadReads(f.db),decode=vi.spyOn(codexCodec,"decodeCodexCheckpoint");try{expect(f.store.readSourceForIngestion(f.id,context).checkpoint).not.toBeNull();expect(payload.reads()).toBe(1);expect(decode).toHaveBeenCalled();}finally{payload.restore();decode.mockRestore();}expect(allRows(f.db)).toEqual(before);
});
it.each([4194305,1])("oversized SQL payload recorded bytes %i rejected before raw payload read",async recorded=>{
 const f=await fixture();f.db.exec("ALTER TABLE source_parser_checkpoints RENAME TO constrained_checkpoint; CREATE TABLE source_parser_checkpoints AS SELECT * FROM constrained_checkpoint; DROP TABLE constrained_checkpoint");f.db.prepare("UPDATE source_parser_checkpoints SET checkpoint_json=CAST(zeroblob(4194305) AS TEXT),checkpoint_bytes=? WHERE source_id=?").run(recorded,f.id);const before=allRows(f.db),payload=countRawPayloadReads(f.db),decode=vi.spyOn(codexCodec,"decodeCodexCheckpoint");try{expect(()=>f.store.readSourceForIngestion(f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(payload.reads()).toBe(0);expect(decode).not.toHaveBeenCalled();}finally{payload.restore();decode.mockRestore();}expect(allRows(f.db)).toEqual(before);
});

it("double-resigned token count-order mutation rejects at durable read before replay or writes",async()=>{
 const {scanSources,SCAN_LIMITS}=await import("../src/scanner/scan-run.js");
 const f=await fixture(ordinary,SCAN_LIMITS.fileBytes),genuine=f.store.readSourceForIngestion(f.id,context),publicBefore=f.store.readSource(f.id),projectionBefore=projection(f.db,f.id);
 expect(genuine.checkpoint).not.toBeNull();
 const ingest=vi.spyOn(CodexAdapter.prototype,"ingest"),replace=vi.fn(f.store.replaceSourceSnapshotWithCheckpoint),legacyReplace=vi.fn(f.store.replaceSourceSnapshot),watched={...f.store,replaceSourceSnapshotWithCheckpoint:replace,replaceSourceSnapshot:legacyReplace};
 const genuineRows=allRows(f.db);
 expect((await scanSources(watched,context,[{provider:"codex",path:f.path}])).sources[0]).toMatchObject({status:"unchanged",reusedRevision:1});
 expect(ingest).not.toHaveBeenCalled();expect(replace).not.toHaveBeenCalled();expect(legacyReplace).not.toHaveBeenCalled();expect(allRows(f.db)).toEqual(genuineRows);
 const row:any=f.db.prepare("SELECT * FROM source_parser_checkpoints WHERE source_id=?").get(f.id),outer=JSON.parse(row.checkpoint_json),state=JSON.parse(outer.payload);
 expect(outer.schema).toBe("agentprof.codex-checkpoint/v1");
 const holder=state.state.usage.find((entry:any)=>entry[1].source==="response_usage")[1],original=holder.counts;
 expect(Object.keys(original)).toEqual(["input","output","cachedInput","cacheWriteInput","reasoningOutput","total"]);
 holder.counts=Object.fromEntries(Object.entries(original).reverse());expect(holder.counts).toEqual(original);expect(Object.keys(holder.counts)).not.toEqual(Object.keys(original));
 const payload=JSON.stringify(state),token=JSON.stringify({schema:outer.schema,payload,tag:hmac("source",outer.schema,sha(payload))});
 expect(Buffer.byteLength(token)).toBe(row.checkpoint_bytes);
 f.db.prepare("UPDATE source_parser_checkpoints SET checkpoint_json=?,checkpoint_bytes=? WHERE source_id=?").run(token,Buffer.byteLength(token),f.id);resign(f.db,f.id);
 expect(f.db.prepare("SELECT generation_seal FROM source_parser_checkpoints WHERE source_id=?").get(f.id)!.generation_seal).toBe(seal(f.db,f.id));
 expect(projection(f.db,f.id)).toBe(projectionBefore);expect(f.store.readSource(f.id)).toEqual(publicBefore);
 const before=allRows(f.db),decode=vi.spyOn(codexCodec,"decodeCodexCheckpoint");
 expect(()=>f.store.readSourceForIngestion(f.id,context)).toThrowError(expect.objectContaining({code:"DATABASE_ACCESS_FAILED"}));expect(decode).toHaveBeenCalledTimes(1);
 const failed=await scanSources(watched,context,[{provider:"codex",path:f.path}]);
 expect(failed).toMatchObject({stopReason:"storage_failure",counts:{failed:1,committed:0,unchanged:0}});expect(failed.sources[0]).toMatchObject({errorCode:"DATABASE_ACCESS_FAILED",revisionRead:false});expect(decode).toHaveBeenCalledTimes(2);
 expect(ingest).not.toHaveBeenCalled();expect(replace).not.toHaveBeenCalled();expect(legacyReplace).not.toHaveBeenCalled();expect(allRows(f.db)).toEqual(before);
});
