import { SafeError } from "../privacy/diagnostics.js";
import type { SourceInvocationTimeline, TimelineCount, TimelinePartition } from "./invocation-timeline.js";
import { validateTimelinePartition } from "./invocation-timeline.js";
const e=(v:unknown):string=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const n=(v:number|null):string=>v===null?"unknown":e(v);
const omissions=(c:TimelineCount,label:string)=>`<p class="omission">${e(label)}: ${c.shown} shown / ${c.total} total · ${c.omitted} omitted by display bounds</p>`;
const meaning="Observed invocation latency only, not tool runtime, task elapsed time, Active Time, API latency, critical path, avoidable work or savings. Blank time is unattributed.";
export function renderInvocationTimelineNotice(t:SourceInvocationTimeline & {selection:{sessions:TimelineCount}}):string{
 return `<section class="panel" id="invocation-timeline-notice"><h3>Observed invocation timeline</h3><p class="state">Native assessment: ${e(t.assessment)} · suppression: ${e(t.suppressionReason??"none")}</p><p class="context">${meaning}</p><p class="context">Only admitted Claude invocation boundaries can be positioned. Codex positioning is unsupported. The selected source prefix does not prove complete session history. Start boundaries rely on the validated stored adapter contract; ordinary call observations retain no timestamp.</p>${omissions(t.selection.sessions,"Timeline sessions")}${t.partitions.length===0?"<p class=\"notice\">No timeline session is displayed. This is not a healthy zero or proof of no work.</p>":""}</section>`;
}
/** Pure renderer of validated, bounded, owned relative offsets. No source identifiers or timestamps. */
export function renderSourceInvocationTimeline(p:TimelinePartition,sessionOrdinal:number):string{
 validateTimelinePartition(p);if(!Number.isSafeInteger(sessionOrdinal)||sessionOrdinal<1||sessionOrdinal>6)throw new SafeError("REPORT_LIMIT");
 const prefix=`invocation-timeline-${sessionOrdinal}`,c=p.coverage,d=p.display;
 const metrics=`<dl class="timeline-metrics"><div><dt>Interval length sum S</dt><dd class="metric">${n(p.intervalLengthSumMs)} ms</dd></div><div><dt>Interval union U</dt><dd class="metric">${n(p.intervalUnionMs)} ms</dd></div><div><dt>Multiplicity-weighted excess S − U</dt><dd class="metric">${n(p.excessMs)} ms</dd></div></dl>`;
 const coverage=`<p><strong>Positioned ${c.positionedN} / admitted ${c.admittedTerminalN}</strong> · excluded ${c.excludedN} · unsafe endpoint differences ${c.unsafeDifferenceN}</p><p class="context">Boundary coverage: ${c.admittedTerminalN===0?"unknown (no admitted terminal calls)":c.complete?"complete for admitted terminal calls":"incomplete for admitted terminal calls"}. Complete boundaries do not mean complete history or a fraction of wall time.</p><details><summary>Boundary exclusions</summary><dl>${Object.entries(c.exclusions).map(([k,v])=>`<div><dt>${e(k)}</dt><dd>${v}</dd></div>`).join("")}</dl></details>`;
 let geometry:string;
 if(d.state==="unavailable")geometry=`<p class="notice">Timeline drawing unavailable: ${e(d.reason)}. Exact native metrics and coverage above are retained; unavailable measurements remain unknown.</p>`;
 else{
  const span=d.axisSpanMs!,rows=d.rows!,height=rows.length*28+38;
  const title=`Session ${sessionOrdinal}: observed invocation relative offsets`,description=`One invocation per row; relative milliseconds from the earliest positioned start. Full axis span ${span} ms. ${d.counts.shown} of ${d.counts.total} positioned invocations shown. Exact values and terminal status follow in the table. Zero-length point radius is a visibility aid, not elapsed duration.`;
  const narrow=span>0&&rows.some(r=>r.intervalLengthMs>0&&r.intervalLengthMs/span*1000<1);
  const svg=`<svg class="invocation-chart" viewBox="0 0 1000 ${height}" role="img" aria-labelledby="${prefix}-title ${prefix}-description"><title id="${prefix}-title">${e(title)}</title><desc id="${prefix}-description">${e(description)}</desc><text class="invocation-tick" x="0" y="14">0 ms</text><text class="invocation-tick" x="1000" y="14" text-anchor="end">${span} ms</text>${rows.map((r,i)=>{
   const x=span===0?0:r.startOffsetMs/span*1000,width=span===0?0:r.intervalLengthMs/span*1000,y=24+i*28;
   const label=`Invocation ${r.ordinal}, ${r.status}, ${r.startOffsetMs} to ${r.endOffsetMs} ms, length ${r.intervalLengthMs} ms`;
   return `<g><title>${e(label)}</title>${r.intervalLengthMs===0?`<circle class="invocation-zero-point" cx="${x}" cy="${y+8}" r="4"${r.status==="failed"?' stroke-dasharray="2 2"':""}></circle>`:`<rect class="invocation-interval" x="${x}" y="${y}" width="${width}" height="16"${r.status==="failed"?' stroke-dasharray="4 2"':""}></rect>`}</g>`;
  }).join("")}</svg>`;
  const table=`<div class="table-wrap" tabindex="0" role="region" aria-labelledby="${prefix}-caption"><table><caption id="${prefix}-caption">Exact observed invocation offsets · milliseconds · Session ${sessionOrdinal}</caption><thead><tr><th scope="col">Invocation</th><th scope="col">Command / tool cohort</th><th scope="col">Terminal status</th><th scope="col">Start offset ms</th><th scope="col">End offset ms</th><th scope="col">Interval length ms</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">Invocation ${r.ordinal}</th><td><p>${e(r.group.toolName??r.group.kind)} · ${e(r.group.category)}</p><p class="mono">${e(r.group.commandPattern??"unknown pattern")}</p><p class="context">Kind: ${e(r.group.kind)}</p></td><td>${e(r.status)}${r.status==="failed"?" · × dashed outline":""}${r.intervalLengthMs===0?" · zero-length point":""}</td><td>${r.startOffsetMs}</td><td>${r.endOffsetMs}</td><td>${r.intervalLengthMs}</td></tr>`).join("")}</tbody></table></div>`;
  geometry=`<p class="context">Relative axis: 0 to ${span} ms, calculated over every positioned invocation before row limits. One invocation per row; rows are not physical workers. This axis is not task elapsed time.</p>${span===0?"<p class=\"notice\">Zero-span axis: point marker at 0 ms. Its radius is a visibility aid and does not encode nonzero duration.</p>":""}${narrow?"<p class=\"notice\">Scale warning: some positive intervals are below chart resolution at this viewport scale. Bars are not widened; the table retains exact milliseconds.</p>":""}${svg}${table}`;
 }
 return `<section class="panel invocation-timeline" id="${prefix}"><p class="eyebrow">Session ${sessionOrdinal} · positioned invocation boundaries</p><h3>Observed invocation timeline</h3><p class="state">Native status: ${e(p.status)} · reason: ${e(p.reason??"none")}</p>${metrics}${coverage}<p class="context">Three identical 10-second invocations give S=30s, U=10s, excess=20s. Excess is multiplicity-weighted overlap, not concurrent wall time.</p><p class="context">${meaning}</p>${omissions(d.counts,"Positioned invocation rows")}${d.counts.omitted>0&&d.state==="available"?"<p class=\"notice\">Drawing is truncated by the twenty-row display bound. Native metrics, boundary coverage and full axis are unchanged.</p>":""}${geometry}</section>`;
}
