/** Selected semantic tokens from design/tokens.css; no dynamic declarations. */
export const REPORT_CSS=`
:root{color-scheme:dark light;--canvas:#111315;--surface:#191c20;--raised:#23272d;--text:#f5f6f7;--muted:#b2b8c2;--ember:#ff8a3d;--brand-text:#ffab73;--observed:#c3acf2;--line:#3b414a}
*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--text);font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1200px;margin:auto;padding:32px 24px 64px}header{border-bottom:1px solid var(--line);padding:16px 0 32px;margin-bottom:32px}.wordmark{font-weight:800;letter-spacing:-.04em;font-size:28px;color:var(--brand-text)}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:12px;font-weight:700;color:var(--muted)}h1{font-size:clamp(28px,5vw,48px);letter-spacing:-.04em;line-height:1.15;max-width:850px;margin:16px 0}h2{font-size:24px;line-height:1.3;margin:0 0 16px}h3{font-size:18px;margin:0 0 12px}h4{margin:16px 0 8px}.lead{color:var(--muted);max-width:850px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.panel,.card{border:1px solid var(--line);background:var(--surface);border-radius:10px;padding:24px;margin:0 0 24px;min-width:0}.card{border-top:3px solid var(--ember)}.metric{font-size:28px;font-weight:750;font-variant-numeric:tabular-nums;line-height:1.2}.muted{color:var(--muted)}.badge{display:inline-block;border:1px solid var(--line);border-radius:6px;padding:4px 8px;margin:4px 8px 4px 0;font-size:12px}.mono,code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;overflow-wrap:anywhere}.context{overflow-wrap:anywhere;font-size:13px;color:var(--muted)}.table-wrap{overflow-x:auto;margin:16px 0}table{width:100%;border-collapse:collapse;font-size:13px}caption{text-align:left;font-weight:650;padding:8px 0}th,td{text-align:right;vertical-align:top;padding:12px 8px;border-bottom:1px solid var(--line);font-variant-numeric:tabular-nums}th:first-child,td:first-child{text-align:left;min-width:160px}th{color:var(--muted);font-size:12px}td p{margin:0}.bar{display:block;width:100%;max-width:180px;height:8px;margin-top:8px}.bar rect{fill:var(--ember)}a{color:var(--brand-text);text-underline-offset:4px;display:inline-block;min-height:44px;padding:8px}nav{display:flex;flex-wrap:wrap;gap:8px}nav a,summary{min-height:44px;padding:8px;display:inline-block}summary{display:list-item;cursor:pointer;font-weight:600}a:focus-visible,summary:focus-visible,.table-wrap:focus-visible{outline:3px solid var(--observed);outline-offset:4px}details{border-top:1px solid var(--line);padding-top:8px;margin-top:16px}dl{margin:0}dt{color:var(--muted);font-size:12px}dd{margin:0 0 12px;overflow-wrap:anywhere}.pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.notice{border-left:3px solid var(--observed);padding:8px 16px;color:var(--muted)}.state{font-weight:650;color:var(--observed)}.omission{font-size:12px;color:var(--muted)}footer{border-top:1px solid var(--line);padding-top:24px;font-size:13px;color:var(--muted)}p{overflow-wrap:anywhere}section{scroll-margin-top:16px}
.native-details{border-top:1px solid var(--line);padding-top:16px;margin:16px 0 24px}.native-share-bar{display:block;width:100%;min-width:100px;max-width:180px;height:8px;margin-top:8px}.native-share-track{fill:var(--raised)}.native-share-value{fill:var(--observed)}.native-details th p{font-weight:400;margin:0}.native-details th .mono{color:var(--text)}
.timeline-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:16px 0}.invocation-chart{display:block;width:100%;height:auto;margin:16px 0;overflow:visible}.invocation-interval,.invocation-zero-point{fill:var(--observed);stroke:var(--text);stroke-width:1}.invocation-tick{fill:var(--text);font-size:12px}.invocation-timeline td:nth-child(n+4){white-space:nowrap}
.token-evidence-bar{display:block;width:100%;height:16px;margin:16px 0}.token-evidence-selected{fill:var(--observed)}.token-evidence-duplicate{fill:var(--ember)}.token-evidence-excluded{fill:var(--muted)}
@media(prefers-color-scheme:light){:root{--canvas:#f5f6f7;--surface:#ffffff;--raised:#edf0f3;--text:#171a1e;--muted:#555d69;--brand-text:#944200;--line:#cdd2d9;--observed:#66508c}}
@media(max-width:640px){main{padding:16px 12px 32px}.grid,.pair,.timeline-metrics{grid-template-columns:1fr}.panel,.card{padding:16px}h2{font-size:21px}th,td{padding:8px}.context{font-size:12px}}
@media print{:root{--canvas:#ffffff;--surface:#ffffff;--text:#171a1e;--muted:#555d69;--line:#cccccc;--brand-text:#944200;--observed:#66508c}body{font-size:10pt}main{max-width:none;padding:0}.panel,.card{break-inside:avoid;padding:12px;margin:0 0 16px}.table-wrap{overflow:visible}table{font-size:8pt}nav{display:none}details>*{display:block}summary{list-style:none}.bar,.native-share-bar,.invocation-chart,.token-evidence-bar{-webkit-print-color-adjust:exact;print-color-adjust:exact}a{color:inherit;text-decoration:none}}
`;
