-- Genuine schema7 DDL generated by immutable PR168 17fa6b3f511e705294fd84206504efad0ba9f978
-- src/db/database.ts Git blob c672cc28f07527ef61680093ceef9188e695d304
-- Generated from its original migrate() in an empty DatabaseSync, not current code.
CREATE TABLE directory_membership_members (
          root_id TEXT NOT NULL REFERENCES directory_membership_roots(root_id),
          source_id TEXT NOT NULL CHECK(length(CAST(source_id AS BLOB)) <= 128),
          source_revision INTEGER NOT NULL CHECK(source_revision BETWEEN 1 AND 9007199254740991),
          observation TEXT NOT NULL CHECK(observation IN ('observed','not_observed')),
          PRIMARY KEY(root_id,source_id)
        ) STRICT;
CREATE TABLE directory_membership_roots (
          root_id TEXT PRIMARY KEY CHECK(length(CAST(root_id AS BLOB)) <= 128),
          provider TEXT NOT NULL CHECK(provider IN ('codex','claude')),
          contract_version INTEGER NOT NULL CHECK(contract_version=1),
          key_id TEXT NOT NULL REFERENCES source_store_identity(key_id),
          root_fingerprint TEXT NOT NULL CHECK(length(CAST(root_fingerprint AS BLOB)) <= 128),
          revision INTEGER NOT NULL CHECK(revision BETWEEN 1 AND 9007199254740991),
          member_count INTEGER NOT NULL CHECK(member_count BETWEEN 0 AND 4096),
          manifest_bytes INTEGER NOT NULL CHECK(manifest_bytes BETWEEN 2 AND 1048576),
          seal TEXT NOT NULL CHECK(length(CAST(seal AS BLOB)) <= 128)
        ) STRICT;
CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY) STRICT;
CREATE TABLE settings (key TEXT PRIMARY KEY CHECK(key IN ('normalization_version', 'key_version')), value INTEGER NOT NULL) STRICT;
CREATE TABLE source_cache_evidence (
          source_id TEXT PRIMARY KEY REFERENCES source_event_headers(source_id),
          contract_version INTEGER NOT NULL CHECK(contract_version = 1),
          content_fingerprint TEXT NOT NULL CHECK(length(CAST(content_fingerprint AS BLOB)) <= 128)
        ) STRICT;
CREATE TABLE source_event_contributions (
          source_id TEXT NOT NULL REFERENCES source_event_headers(source_id),
          event_id TEXT NOT NULL,
          event_json TEXT NOT NULL CHECK(length(CAST(event_json AS BLOB)) <= 65536),
          PRIMARY KEY(source_id, event_id)
        ) STRICT;
CREATE TABLE source_event_headers (
          source_id TEXT PRIMARY KEY,
          provider TEXT NOT NULL CHECK(provider IN ('codex', 'claude')),
          parser_version INTEGER NOT NULL CHECK(parser_version BETWEEN 1 AND 9007199254740991),
          normalization_version INTEGER NOT NULL CHECK(normalization_version = 1),
          key_version INTEGER NOT NULL CHECK(key_version = 1),
          key_id TEXT NOT NULL REFERENCES source_store_identity(key_id),
          completed_offset INTEGER NOT NULL CHECK(completed_offset BETWEEN 0 AND 9007199254740991),
          observed_size INTEGER NOT NULL CHECK(observed_size BETWEEN completed_offset AND 9007199254740991),
          boundary_fingerprint TEXT,
          revision INTEGER NOT NULL CHECK(revision BETWEEN 1 AND 9007199254740991),
          availability TEXT NOT NULL CHECK(availability IN ('available', 'unavailable')),
          event_count INTEGER NOT NULL CHECK(event_count BETWEEN 0 AND 4096),
          event_bytes INTEGER NOT NULL CHECK(event_bytes BETWEEN 0 AND 16777216)
        ) STRICT;
CREATE TABLE source_metric_contributions (
          source_id TEXT NOT NULL REFERENCES source_metric_headers(source_id),
          kind TEXT NOT NULL CHECK(kind IN ('turn', 'usage', 'observation', 'diagnostic', 'capabilities')),
          ordinal INTEGER NOT NULL CHECK(ordinal BETWEEN 0 AND 8191),
          row_id TEXT,
          row_json TEXT NOT NULL CHECK(length(CAST(row_json AS BLOB)) <= 65536),
          PRIMARY KEY(source_id, kind, ordinal),
          UNIQUE(source_id, kind, row_id)
        ) STRICT;
CREATE TABLE source_metric_headers (
          source_id TEXT PRIMARY KEY REFERENCES source_event_headers(source_id),
          contract_version INTEGER NOT NULL CHECK(contract_version = 1),
          turn_count INTEGER NOT NULL CHECK(turn_count BETWEEN 0 AND 4096),
          usage_count INTEGER NOT NULL CHECK(usage_count BETWEEN 0 AND 4096),
          observation_count INTEGER NOT NULL CHECK(observation_count BETWEEN 0 AND 8192),
          diagnostic_count INTEGER NOT NULL CHECK(diagnostic_count BETWEEN 0 AND 8192),
          metric_bytes INTEGER NOT NULL CHECK(metric_bytes BETWEEN 0 AND 16777216)
        ) STRICT;
CREATE TABLE source_parser_checkpoints (
          source_id TEXT PRIMARY KEY REFERENCES source_event_headers(source_id),
          contract_version INTEGER NOT NULL CHECK(contract_version = 1),
          next_ordinal INTEGER NOT NULL CHECK(next_ordinal BETWEEN 0 AND 32768),
          max_file_bytes INTEGER NOT NULL CHECK(max_file_bytes BETWEEN 1 AND 67108864),
          max_records INTEGER NOT NULL CHECK(max_records BETWEEN 1 AND 32768 AND next_ordinal <= max_records),
          max_line_bytes INTEGER NOT NULL CHECK(max_line_bytes BETWEEN 1 AND 1048576),
          checkpoint_bytes INTEGER NOT NULL CHECK(checkpoint_bytes BETWEEN 1 AND 4194304),
          checkpoint_json TEXT NOT NULL CHECK(length(CAST(checkpoint_json AS BLOB)) = checkpoint_bytes),
          adapter_limits_fingerprint TEXT NOT NULL CHECK(length(CAST(adapter_limits_fingerprint AS BLOB)) = 64),
          generation_seal TEXT NOT NULL CHECK(length(CAST(generation_seal AS BLOB)) <= 128)
        ) STRICT;
CREATE TABLE source_relationship_contributions (
          source_id TEXT NOT NULL REFERENCES source_relationship_headers(source_id),
          kind TEXT NOT NULL CHECK(kind IN ('metadata', 'wrapper', 'message')),
          ordinal INTEGER NOT NULL CHECK(ordinal BETWEEN 0 AND 8191),
          row_id TEXT NOT NULL,
          row_json TEXT NOT NULL CHECK(length(CAST(row_json AS BLOB)) <= 65536),
          PRIMARY KEY(source_id, kind, ordinal),
          UNIQUE(source_id, kind, row_id)
        ) STRICT;
CREATE TABLE source_relationship_headers (
          source_id TEXT PRIMARY KEY REFERENCES source_event_headers(source_id),
          contract_version INTEGER NOT NULL CHECK(contract_version = 1),
          capture_policy_version INTEGER NOT NULL CHECK(capture_policy_version BETWEEN 1 AND 9007199254740991),
          status TEXT NOT NULL CHECK(status IN ('captured', 'unavailable')),
          reason TEXT CHECK(reason IS NULL OR reason = 'relationship_budget_exceeded'),
          metadata_count INTEGER NOT NULL CHECK(metadata_count BETWEEN 0 AND 8192),
          wrapper_count INTEGER NOT NULL CHECK(wrapper_count BETWEEN 0 AND 4096),
          message_count INTEGER NOT NULL CHECK(message_count BETWEEN 0 AND 8192),
          relationship_bytes INTEGER NOT NULL CHECK(relationship_bytes BETWEEN 0 AND 4194304),
          CHECK((status='captured' AND reason IS NULL) OR (status='unavailable' AND reason='relationship_budget_exceeded' AND metadata_count=0 AND wrapper_count=0 AND message_count=0 AND relationship_bytes=0))
        ) STRICT;
CREATE TABLE source_store_identity (
          singleton INTEGER PRIMARY KEY CHECK(singleton = 1),
          key_id TEXT NOT NULL UNIQUE CHECK(length(key_id) = 32)
        ) STRICT;
INSERT INTO settings(key,value) VALUES('key_version',1),('normalization_version',1);
INSERT INTO schema_migrations(version) VALUES (1),(2),(3),(4),(5),(6),(7);
PRAGMA user_version=7;
